'------------------------------------------------------------------------------
' <auto-generated>
'     このコードはツールによって生成されました。
'     ランタイム バージョン:4.0.30319.42000
'
'     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
'     コードが再生成されるときに損失したりします。
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Namespace ServiceReference1
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ServiceModel.ServiceContractAttribute(ConfigurationName:="ServiceReference1.apiSoap")>  _
    Public Interface apiSoap
        
        'CODEGEN: 名前空間 http://tempuri.org/ の要素名 chkNo_key が nillable に設定されていないため、メッセージ コントラクトを生成しています
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/SaveIMG", ReplyAction:="*")>  _
        Function SaveIMG(ByVal request As ServiceReference1.SaveIMGRequest) As ServiceReference1.SaveIMGResponse
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class SaveIMGRequest
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="SaveIMG", [Namespace]:="http://tempuri.org/", Order:=0)>  _
        Public Body As ServiceReference1.SaveIMGRequestBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As ServiceReference1.SaveIMGRequestBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class SaveIMGRequestBody
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=0)>  _
        Public chkNo_key As String
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=1)>  _
        Public line_id As String
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=2)>  _
        Public chk_method_id As String
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=3)>  _
        Public img() As Byte
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal chkNo_key As String, ByVal line_id As String, ByVal chk_method_id As String, ByVal img() As Byte)
            MyBase.New
            Me.chkNo_key = chkNo_key
            Me.line_id = line_id
            Me.chk_method_id = chk_method_id
            Me.img = img
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class SaveIMGResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="SaveIMGResponse", [Namespace]:="http://tempuri.org/", Order:=0)>  _
        Public Body As ServiceReference1.SaveIMGResponseBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As ServiceReference1.SaveIMGResponseBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class SaveIMGResponseBody
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=0)>  _
        Public SaveIMGResult As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal SaveIMGResult As String)
            MyBase.New
            Me.SaveIMGResult = SaveIMGResult
        End Sub
    End Class
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Public Interface apiSoapChannel
        Inherits ServiceReference1.apiSoap, System.ServiceModel.IClientChannel
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Partial Public Class apiSoapClient
        Inherits System.ServiceModel.ClientBase(Of ServiceReference1.apiSoap)
        Implements ServiceReference1.apiSoap
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String)
            MyBase.New(endpointConfigurationName)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As String)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal binding As System.ServiceModel.Channels.Binding, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(binding, remoteAddress)
        End Sub
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function ServiceReference1_apiSoap_SaveIMG(ByVal request As ServiceReference1.SaveIMGRequest) As ServiceReference1.SaveIMGResponse Implements ServiceReference1.apiSoap.SaveIMG
            Return MyBase.Channel.SaveIMG(request)
        End Function
        
        Public Function SaveIMG(ByVal chkNo_key As String, ByVal line_id As String, ByVal chk_method_id As String, ByVal img() As Byte) As String
            Dim inValue As ServiceReference1.SaveIMGRequest = New ServiceReference1.SaveIMGRequest()
            inValue.Body = New ServiceReference1.SaveIMGRequestBody()
            inValue.Body.chkNo_key = chkNo_key
            inValue.Body.line_id = line_id
            inValue.Body.chk_method_id = chk_method_id
            inValue.Body.img = img
            Dim retVal As ServiceReference1.SaveIMGResponse = CType(Me,ServiceReference1.apiSoap).SaveIMG(inValue)
            Return retVal.Body.SaveIMGResult
        End Function
    End Class
End Namespace
